/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prashant.stocks;

import com.prashant.resources.dir;
import com.prashant.resources.query;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Prashant
 */
class MyCustomFilter extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        // Allow only directories, or files with ".txt" extension
        return file.isDirectory() || file.getAbsolutePath().endsWith(".jpg") || file.getAbsolutePath().endsWith(".JPG") || file.getAbsolutePath().endsWith(".jpeg") || file.getAbsolutePath().endsWith(".JPEG") || file.getAbsolutePath().endsWith(".png") || file.getAbsolutePath().endsWith(".gif") || file.getAbsolutePath().endsWith(".ico");
    }

    @Override
    public String getDescription() {
        // This description will be displayed in the dialog,
        // hard-coded = ugly, should be done via I18N
        return "Images (*.jpeg or *.jpg or *.png or *.gif or *.ico)";
    }
}

public class addItem extends javax.swing.JFrame {

    /**
     * Creates new form addItem
     */
    public addItem() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO.png")));
    }

    public static String image = "";
    int posX = 0, posY = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        items = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mrp = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        fileChooser.setCurrentDirectory(new java.io.File("C:\\"));
            fileChooser.setDialogTitle("Select The Image");
            fileChooser.setFileFilter(new MyCustomFilter());
            fileChooser.setBorder(null);
            fileChooser.setName("fileChooser"); // NOI18N

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("STOCK MANAGER - Add Item");
            setName("Add Item"); // NOI18N
            setUndecorated(true);
            setPreferredSize(new java.awt.Dimension(891, 610));
            addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    formMouseDragged(evt);
                }
            });
            addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    formMouseClicked(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    formMousePressed(evt);
                }
            });
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel1.setBackground(new java.awt.Color(25, 25, 25));
            jPanel1.setForeground(new java.awt.Color(204, 204, 204));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/stocks/LOGOS.png"))); // NOI18N
            jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 63, -1, -1));

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(204, 204, 204));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("STOCK MANAGER");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 76, 840, -1));

            jPanel2.setBackground(new java.awt.Color(102, 102, 102));
            jPanel2.setForeground(new java.awt.Color(102, 102, 102));

            jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("ADD ITEM");

            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/resources/Add Item - Copy.png"))); // NOI18N

            jLabel5.setBackground(new java.awt.Color(153, 153, 153));
            jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 102, 102));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("X ");
            jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel5.setOpaque(true);
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel5MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel5MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel5MouseExited(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 570, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 891, -1));

            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/resources/Home.png"))); // NOI18N
            jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel6MouseClicked(evt);
                }
            });
            jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

            jPanel3.setBackground(new java.awt.Color(255, 255, 255));
            jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(25, 25, 25));
            jLabel7.setText("Product ID : ");
            jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

            id.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            id.setForeground(new java.awt.Color(102, 102, 102));
            id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            id.setBorder(null);
            id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            id.setOpaque(false);
            jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 390, 30));

            jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 410, 10));

            name.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            name.setForeground(new java.awt.Color(102, 102, 102));
            name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            name.setBorder(null);
            name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            name.setOpaque(false);
            jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 390, 30));

            jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 410, 10));

            jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(25, 25, 25));
            jLabel8.setText("Product Name : ");
            jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 119, -1, -1));

            items.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            items.setForeground(new java.awt.Color(102, 102, 102));
            items.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            items.setBorder(null);
            items.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            items.setOpaque(false);
            jPanel3.add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 390, 30));

            jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 410, 10));

            jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(25, 25, 25));
            jLabel9.setText("Total Items : ");
            jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 189, -1, -1));

            jLabel10.setBackground(new java.awt.Color(204, 204, 204));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jLabel10.setOpaque(true);
            jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 40, 240, 257));

            jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(25, 25, 25));
            jLabel11.setText("Price : ");
            jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 266, -1, -1));

            mrp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            mrp.setForeground(new java.awt.Color(102, 102, 102));
            mrp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            mrp.setBorder(null);
            mrp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            mrp.setOpaque(false);
            jPanel3.add(mrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 257, 398, 30));

            jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 287, 410, 10));

            jLabel12.setBackground(new java.awt.Color(204, 204, 204));
            jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel12.setText("BROWSE THE IMAGE");
            jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel12.setOpaque(true);
            jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel12MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel12MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel12MouseExited(evt);
                }
            });
            jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 315, 150, 26));

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);

            jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 355, 556, -1));

            jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(25, 25, 25));
            jLabel13.setText("DETAILS : ");
            jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 335, -1, -1));

            jLabel14.setBackground(new java.awt.Color(204, 204, 204));
            jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel14.setText("ADD THIS ITEM");
            jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel14.setOpaque(true);
            jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel14MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel14MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel14MouseExited(evt);
                }
            });
            jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 381, 150, 26));

            jLabel15.setBackground(new java.awt.Color(204, 204, 204));
            jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel15.setText("CANCEL");
            jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel15.setOpaque(true);
            jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel15MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel15MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel15MouseExited(evt);
                }
            });
            jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 425, 150, 26));

            getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 171, 900, 490));

            setSize(new java.awt.Dimension(883, 650));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        jLabel15.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (!(id.getText().equals("") || id.getText() == null)) {
            int returnVal = fileChooser.showOpenDialog(this);
            image = "Data/" + id.getText() + "/Icon.jpg";
            File dst = new File("Data/" + id.getText().trim());
            dst.mkdirs();
            dst = new File(image);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try {
                    File file = fileChooser.getSelectedFile();
                    dir.resImage(file, dst.getAbsolutePath());
                    jLabel10.setBackground(Color.WHITE);
                    jLabel10.setIcon(new ImageIcon(image));
                    Files.copy(file.toPath(), new File(image.replace("/Icon.jpg", "/Pic.jpg")).toPath());
                } catch (IOException ex) {
                    Logger.getLogger(addItem.class.getName()).log(Level.SEVERE, null, ex);
                    dir.writeFile("errLog", "Error copying the file...\n");
                }
            } else {
                dir.writeFile("errLog", "File access cancelled by user.\n");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter the details first...");
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        jLabel14.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        String PID, Pname, Titems, Pprice, des;
        PID = id.getText().trim();
        Pname = name.getText().trim();
        Titems = items.getText().trim();
        Pprice = mrp.getText().trim();
        des = jTextArea1.getText();
        int tworth = Integer.parseInt(Titems) * Integer.parseInt(Pprice);
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        java.util.Date today = java.util.Calendar.getInstance().getTime();
        String date = df.format(today);

        if (!(new File("Data/" + PID).exists())) {
            new File("Data/" + PID).mkdirs();
        }
        dir.writeFile(PID + "/Description", des);
        des = "Data/" + PID + "/Description";

        String Query1, Query2;
        Query1 = "INSERT INTO Products(PID,Name,Items,Price,TotalWorth,LastUpdated,Description,Image) VALUES('" + PID + "','" + Pname + "'," + Titems + "," + Pprice + "," + tworth + ",'" + date + "','" + des + "','" + image + "')";
        PID = PID.trim().replaceAll(" ", "");
        Query2 = "CREATE TABLE `" + PID + "`( Items INT, Price INT, Total Int, Date Varchar(25))";
        query.runCUD(Query1);
        query.runCUD(Query2);
        System.out.println(PID + " has been created...");
        JOptionPane.showMessageDialog(this, "Item added to the stock...");
        new addItem().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to go Home...") == JOptionPane.YES_OPTION) {
            new Home().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField id;
    private javax.swing.JTextField items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
