/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prashant.stocks;

import com.prashant.resources.dir;
import com.prashant.resources.query;
import static com.prashant.stocks.addItem.image;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Prashant
 */
public class updateStock extends javax.swing.JFrame {

    class MyCustomFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".jpg") || file.getAbsolutePath().endsWith(".JPG") || file.getAbsolutePath().endsWith(".jpeg") || file.getAbsolutePath().endsWith(".JPEG") || file.getAbsolutePath().endsWith(".png") || file.getAbsolutePath().endsWith(".gif") || file.getAbsolutePath().endsWith(".ico");
        }

        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Images (*.jpeg or *.jpg or *.png or *.gif or *.ico)";
        }
    }

    /**
     * Creates new form updateStock
     */
    public updateStock() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO.png")));
    }

    int posX = 0, posY = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Plist = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        items = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        pcheck = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        outgoing = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        update = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();

        fileChooser.setCurrentDirectory(new java.io.File("C:\\"));
            fileChooser.setDialogTitle("Select The Image");
            fileChooser.setFileFilter(new MyCustomFilter());
            fileChooser.setBorder(null);
            fileChooser.setName("fileChooser"); // NOI18N

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("STOCK MANAGER - Update Stock");
            setName("Update Stock"); // NOI18N
            setUndecorated(true);
            setPreferredSize(new java.awt.Dimension(891, 610));
            addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    formMouseDragged(evt);
                }
            });
            addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    formMouseClicked(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    formMousePressed(evt);
                }
            });
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel3.setBackground(new java.awt.Color(25, 25, 25));
            jPanel3.setForeground(new java.awt.Color(204, 204, 204));
            jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/stocks/LOGOS.png"))); // NOI18N
            jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 63, -1, -1));

            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(204, 204, 204));
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("STOCK MANAGER");
            jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 76, 840, -1));

            jPanel4.setBackground(new java.awt.Color(102, 102, 102));
            jPanel4.setForeground(new java.awt.Color(102, 102, 102));

            jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(255, 255, 255));
            jLabel8.setText("UPDATE STOCK");

            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/resources/Update Stock - Copy.png"))); // NOI18N

            jLabel10.setBackground(new java.awt.Color(153, 153, 153));
            jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 102, 102));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setText("X ");
            jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel10.setOpaque(true);
            jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel10MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel10MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel10MouseExited(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 570, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 891, -1));

            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prashant/resources/Home.png"))); // NOI18N
            jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel11MouseClicked(evt);
                }
            });
            jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

            getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 170));

            jPanel5.setBackground(new java.awt.Color(255, 255, 255));

            jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(25, 25, 25));
            jLabel12.setText("Product : ");

            jLabel19.setBackground(new java.awt.Color(204, 204, 204));
            jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel19.setText("OK");
            jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel19.setOpaque(true);
            jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel19MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel19MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel19MouseExited(evt);
                }
            });

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel20.setForeground(new java.awt.Color(25, 25, 25));
            jLabel20.setText("Items : ");
            jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

            items.setEditable(false);
            items.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            items.setForeground(new java.awt.Color(102, 102, 102));
            items.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            items.setBorder(null);
            items.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            items.setOpaque(false);
            jPanel1.add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 250, 30));

            jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, 10));

            jLabel1.setOpaque(true);
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 20, 200, 230));

            jLabel21.setBackground(new java.awt.Color(204, 204, 204));
            jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel21.setText("UPDATE THE IMAGE");
            jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel21.setName("browseimage"); // NOI18N
            jLabel21.setOpaque(true);
            jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel21MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel21MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel21MouseExited(evt);
                }
            });
            jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 160, 30));

            price.setEditable(false);
            price.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            price.setForeground(new java.awt.Color(102, 102, 102));
            price.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            price.setBorder(null);
            price.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            price.setOpaque(false);
            jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 250, 30));

            jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 270, 10));

            jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel22.setForeground(new java.awt.Color(25, 25, 25));
            jLabel22.setText("Items Taken out from the Stock : ");
            jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

            pcheck.setBackground(new java.awt.Color(255, 255, 255));
            pcheck.setForeground(new java.awt.Color(51, 51, 51));
            pcheck.setText("Update The Price");
            pcheck.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    pcheckMouseClicked(evt);
                }
            });
            jPanel1.add(pcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

            jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel23.setForeground(new java.awt.Color(25, 25, 25));
            jLabel23.setText("Price : ");
            jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

            outgoing.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            outgoing.setForeground(new java.awt.Color(102, 102, 102));
            outgoing.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            outgoing.setBorder(null);
            outgoing.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            outgoing.setOpaque(false);
            jPanel1.add(outgoing, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 250, 30));

            jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 270, 10));

            update.setBackground(new java.awt.Color(204, 204, 204));
            update.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            update.setText("UPDATE");
            update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            update.setOpaque(true);
            update.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    updateMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    updateMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    updateMouseExited(evt);
                }
            });
            jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 160, 40));

            jTextArea1.setEditable(false);
            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);

            jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 570, 190));

            jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
            jRadioButton1.setText("Edit the Description");
            jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButton1ActionPerformed(evt);
                }
            });
            jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel12)
                    .addGap(18, 18, 18)
                    .addComponent(Plist, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(Plist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE))
            );

            getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 900, 530));

            setSize(new java.awt.Dimension(883, 694));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to go Home...") == JOptionPane.YES_OPTION) {
            new Home().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        String str = Plist.getSelectedItem().toString();
        String []ids = str.split("-");
        String ID = ids[0].replaceAll(" ", "");
        System.out.println(ID);
        String Query = "SELECT Items, Price, Description, Image FROM Products WHERE PID = \"" + ID + "\"";
        try{
            ResultSet rs = query.runR(Query);
            if(rs.next()){
                items.setText(rs.getString(1));
                price.setText(rs.getString(2));
                jTextArea1.setText(dir.readFile(rs.getString(3)));
                jLabel1.setBackground(Color.white);
                jLabel1.setIcon(new ImageIcon(rs.getString(4)));                
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Unable to read the database...");
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        jLabel19.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        jLabel19.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        String str[] = Plist.getSelectedItem().toString().split("-");
        String dsti = "Data/" + str[0].replaceAll(" ", "") + "/Icon.jpg";
        File dest = new File(dsti);
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                dir.resImage(file, dest.getAbsolutePath());
                jLabel1.setBackground(Color.WHITE);
                jLabel1.setIcon(new ImageIcon(dsti));
                new File(dsti).delete();
                new File(dsti.replace("/Icon.jpg", "/Pic.jpg")).delete();
                Files.copy(file.toPath(), new File(dsti.replace("/Icon.jpg", "/Pic.jpg")).toPath());
            } catch (IOException ex) {
                Logger.getLogger(addItem.class.getName()).log(Level.SEVERE, null, ex);
                dir.writeFile("errLog", "Error copying the file...\n");
            }
        } else {
            dir.writeFile("errLog", "File access cancelled by user.\n");
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        jLabel21.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jLabel21.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabel21MouseExited

    private void pcheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcheckMouseClicked
        if (pcheck.isSelected()) {
            price.setEditable(true);
        } else {
            price.setEditable(true);
        }
    }//GEN-LAST:event_pcheckMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        int itemLeft = Integer.parseInt(items.getText().trim());
        int items = Integer.parseInt(outgoing.getText().trim());
        int mrp = Integer.parseInt(price.getText().trim());
        String str[] = Plist.getSelectedItem().toString().split("-");
        String ID = str[0].replaceAll(" ", "");
        String Product = str[1].replaceAll(" ", "");
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        java.util.Date today = java.util.Calendar.getInstance().getTime();
        String date = df.format(today);
        String Query1 = "INSERT INTO `" + ID + "` VALUES(" + items + "," + mrp + "," + (items * mrp) + ",\"" + date + "\")";
        String Query2 = "UPDATE Products SET Items = " + (itemLeft - items) + ",Price = " + mrp + ",TotalWorth = " + ((itemLeft - items) * mrp) + ",LastUpdated = \"" + date + "\" WHERE PID = \"" + ID + "\"";
        if (items >= itemLeft) {
            JOptionPane.showMessageDialog(this, "Only " + itemLeft + " items are left...");
        } else {
            new File(ID + "/Description").delete();
            dir.writeFile(ID + "/Description", jTextArea1.getText());
            query.runCUD(Query1);
            query.runCUD(Query2);
            JOptionPane.showMessageDialog(this, "Done...");
            new Home().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(new Color(104, 104, 104));
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_updateMouseExited

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            jTextArea1.setEditable(true);
        } else {
            jTextArea1.setEditable(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox Plist;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField outgoing;
    private javax.swing.JRadioButton pcheck;
    private javax.swing.JTextField price;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
